<a href="https://colab.research.google.com/github/SivarajTechM/AV-CPW/blob/master/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contents

- NumPy vs. Python
- Data Types
- Array Types
- Type Conversions
- Array Creation
- Indexing
- Slicing
- Shape Manipulation


# NumPy vs. Python

- Less Coding in NumPy


In [0]:
# Adding vectors using pure Python

def pythonsum(n):
  a = list(range(n))
  b = list(range(n))
  c = []
  
  for i in range(len(a)):
    a[i] = i ** 2
    b[i] = i ** 3
    c.append(a[i] + b[i])
  
  return c

In [0]:
# Adding vectors in NumPy

import numpy as np

def numpysum(n):
  a = np.arange(n) ** 2
  b = np.arange(n) ** 3
  c = a + b
  return c

numpysum(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

- NumPy is comparatively faster than Python

In [0]:
from datetime import datetime

size = int(input("Enter any large number as size of the array: "))

start_time = datetime.now()
c = pythonsum(size)
time_taken = datetime.now() - start_time

print("Time taken using Python: ", time_taken)


Enter any large number as size of the array: 10000000
Time taken using Python:  0:00:09.631001


In [0]:
size = int(input("Enter any large number as size of the array: "))

start_time = datetime.now()
c = numpysum(size)
time_taken = datetime.now() - start_time

print("Time taken using NumPy: ", time_taken)

Enter any large number as size of the array: 10000000
Time taken using NumPy:  0:00:00.399164


In [0]:
a = np.arange(5)
a.dtype
a.shape


(5,)

In [0]:
for i in range(5): print(i)

In [0]:
print(np.arange(5))

# Introduction to vectors and matrices

* A matrix is a group of numbers or elements which are arranged as a rectangular array

* The matrix's rows and columns are usually indexed by a letter. For *n x m* matrix, *n* represents the number of rows and *m* representes number of columns

* If *n = m* it is a square matrix

$$\begin{bmatrix} 1 & 2 & -1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

* A vector is actually a matrix with one row or one column having more than one element. It can also be defined as a *1-by-m* or *n-by-1* matrix.

* Zero matrix has all 0

* Identity matrix has all diagonal elements as 1 while others are all 0

* When you multiply a matrix with its inverse, the result will be an identity matrix

* Matrix Arithmetic:
  - Matrix Addition:
  
$$\begin{bmatrix} 1 & 4 & 7 \\ 2 & 5 & 8 \end{bmatrix}$$ +  $$\begin{bmatrix} 10 & 14 & 16 \\ 13 & 18 & 21 \end{bmatrix}$$ =  $$\begin{bmatrix} 13 & 18 & 23 \\ 15 & 23 & 29 \end{bmatrix}$$ 
  
  - Matrix Subtraction:
  
  - Matrix Multiplication
  
  - Matrix Division:





In [0]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
print("The type of the array is : ", type(x))

The type of the array is :  <class 'numpy.ndarray'>


In [0]:
print("The shape of the array is : ", x.shape)

The shape of the array is :  (2, 3)


In [0]:
print("The total size is :", x.size)

The total size is : 6


In [0]:
print("The dimension of the array is :", x.ndim)

The dimension of the array is : 2


In [0]:
print("The data types of the array elements are :", x.dtype )

The data types of the array elements are : int64


In [0]:
print("The array consumes :", x.nbytes , " bytes")

The array consumes : 48  bytes


In [0]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.float)
print(x)
print("Memory used: ", x.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
Memory used:  48


In [0]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.complex)
print(x)
print("Memory used: ", x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Memory used:  96


In [0]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.uint32)
print(x)
print("Memory used: ", x.nbytes)

[[1 2 3]
 [4 5 6]]
Memory used:  24


You cannot change the dtype after creating the array. 
However, we can create a copy of the array with a new dtype and with the astype attribute.

In [0]:
x_copy = np.array(x, dtype = np.float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
x_copy_int = x_copy.astype(np.int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

## Effect of dtype: 

Imagine a case where you are trying to identify and calculate the risks of an individual patient who has cancer.

If you have 100,000 records (rows), where each row represents a single patient, and each patient has 100 features (results of some of the tests), you have (100000, 100) arrays:

In [0]:
Data_Cancer= np.random.rand(100000,100)
print("Memory consumption with dtype as ", Data_Cancer.dtype, " : ", Data_Cancer.nbytes)

Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print("Memory consumption with dtype as ", Data_Cancer_New.dtype, " : ",  Data_Cancer_New.nbytes)

Memory consumption with dtype as  float64  :  80000000
Memory consumption with dtype as  float32  :  40000000


# NumPy array operations


## Creating NumPy array from a list:

In [0]:
my_list = [2, 14, 6, 8]

my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

## Arithmetic operations with scalar value:

In [0]:
print(my_array + 2)

print(my_array - 1)

print(my_array * 2)

print(my_array / 2)


[ 4 16  8 10]
[ 1 13  5  7]
[ 4 28 12 16]
[1. 7. 3. 4.]


## Arithmetic operations between arrays:


# Creating Arrays

In [0]:
import numpy as np

# a = np.arange(15)
# a

a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape

(3, 5)

In [0]:
a.ndim

2

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize

8

In [0]:
a.size

15

In [0]:
type(a)

numpy.ndarray

In [0]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [0]:
type(b)

numpy.ndarray

In [0]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [0]:
np.set_printoptions(threshold=np.nan)

ValueError: ignored

# Basic Operations

In [0]:
a = np.array([10,20,30,40])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [0]:
c = a - b
c

array([10, 19, 28, 37])

In [0]:
b ** 2


array([0, 1, 4, 9])

In [0]:
10 * np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [0]:
a < 35

array([ True,  True,  True, False])

![alt text](https://raw.githubusercontent.com/SivarajTechM/shared-public/master/Developer.jpg)